// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file admiral/common/v1/token.proto (package admiral.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admiral/common/v1/token.proto.
 */
export const file_admiral_common_v1_token: GenFile = /*@__PURE__*/
  fileDesc("Ch1hZG1pcmFsL2NvbW1vbi92MS90b2tlbi5wcm90bxIRYWRtaXJhbC5jb21tb24udjEilAQKC0FjY2Vzc1Rva2VuEhQKAmlkGAEgASgJQgi6SAVyA7ABARIbCgl0ZW5hbnRfaWQYAiABKAlCCLpIBXIDsAEBEjoKBG5hbWUYAyABKAlCLLpIKXInEAEYPzIhXlthLXpdKFthLXowLTktXXswLDYxfVthLXowLTldKT8kEjAKCnRva2VuX3R5cGUYBSABKA4yHC5hZG1pcmFsLmNvbW1vbi52MS5Ub2tlblR5cGUSDgoGc2NvcGVzGAYgAygJEjQKBnN0YXR1cxgHIAEoDjIkLmFkbWlyYWwuY29tbW9uLnYxLkFjY2Vzc1Rva2VuU3RhdHVzEjQKDGJpbmRpbmdfdHlwZRgIIAEoDjIeLmFkbWlyYWwuY29tbW9uLnYxLkJpbmRpbmdUeXBlEhIKCmJpbmRpbmdfaWQYCSABKAkSEgoKY3JlYXRlZF9ieRgLIAEoCRIuCgpleHBpcmVzX2F0GAwgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxsYXN0X3VzZWRfYXQYDSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmNyZWF0ZWRfYXQYDiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnJldm9rZWRfYXQYDyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKk8KCVRva2VuVHlwZRIaChZUT0tFTl9UWVBFX1VOU1BFQ0lGSUVEEAASEgoOVE9LRU5fVFlQRV9QQVQQARISCg5UT0tFTl9UWVBFX0FHVBACKnUKC0JpbmRpbmdUeXBlEhwKGEJJTkRJTkdfVFlQRV9VTlNQRUNJRklFRBAAEhUKEUJJTkRJTkdfVFlQRV9VU0VSEAESGAoUQklORElOR19UWVBFX0NMVVNURVIQAhIXChNCSU5ESU5HX1RZUEVfUlVOTkVSEAMqmwEKEUFjY2Vzc1Rva2VuU3RhdHVzEiMKH0FDQ0VTU19UT0tFTl9TVEFUVVNfVU5TUEVDSUZJRUQQABIeChpBQ0NFU1NfVE9LRU5fU1RBVFVTX0FDVElWRRABEh8KG0FDQ0VTU19UT0tFTl9TVEFUVVNfUkVWT0tFRBACEiAKHEFDQ0VTU19UT0tFTl9TVEFUVVNfUk9UQVRJTkcQA0JPWk1idWYuYnVpbGQvZ2VuL2dvL2FkbWlyYWwvY29tbW9uL3Byb3RvY29sYnVmZmVycy9nby9hZG1pcmFsL2NvbW1vbi92MTtjb21tb252MWIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * AccessToken contains token metadata common to all token types (PAT, AGT).
 * The raw token secret is never included in this message — it is only returned
 * once at creation time via the `plain_text_token` field in Create responses.
 *
 * Token CRUD is managed by each parent resource's API:
 *   - PATs:         UserAPI    (/v1/user/tokens)
 *   - Cluster AGTs: ClusterAPI (/v1/clusters/{id}/tokens)
 *   - Runner AGTs:  RunnerAPI  (/v1/runners/{id}/tokens)
 *
 * @generated from message admiral.common.v1.AccessToken
 */
export type AccessToken = Message<"admiral.common.v1.AccessToken"> & {
  /**
   * Unique identifier for the token (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Tenant this token belongs to (UUID).
   *
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * URL-safe, human-readable identifier for the token (e.g., "ci-deploy-key").
   * Unique within the parent resource. Lowercase alphanumeric and hyphens only,
   * must start with a letter and end with an alphanumeric character (1-63 chars).
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * The category of this token.
   *
   * @generated from field: admiral.common.v1.TokenType token_type = 5;
   */
  tokenType: TokenType;

  /**
   * The scopes granted to this token. For PATs, these are user-selected.
   * For AGTs, these are auto-assigned based on the resource type.
   *
   * @generated from field: repeated string scopes = 6;
   */
  scopes: string[];

  /**
   * Current lifecycle status of the token.
   *
   * @generated from field: admiral.common.v1.AccessTokenStatus status = 7;
   */
  status: AccessTokenStatus;

  /**
   * The kind of resource this token is bound to.
   *
   * @generated from field: admiral.common.v1.BindingType binding_type = 8;
   */
  bindingType: BindingType;

  /**
   * The ID of the resource this token is bound to (UUID).
   *
   * @generated from field: string binding_id = 9;
   */
  bindingId: string;

  /**
   * The user who created this token (UUID). For PATs, this is the token owner.
   * For AGTs, this is the administrator who issued the token.
   *
   * @generated from field: string created_by = 11;
   */
  createdBy: string;

  /**
   * When the token expires. If unset, the token does not expire.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 12;
   */
  expiresAt?: Timestamp;

  /**
   * When the token was last used to authenticate an API request.
   *
   * @generated from field: google.protobuf.Timestamp last_used_at = 13;
   */
  lastUsedAt?: Timestamp;

  /**
   * When the token was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 14;
   */
  createdAt?: Timestamp;

  /**
   * When the token was revoked. Only set when status is REVOKED.
   *
   * @generated from field: google.protobuf.Timestamp revoked_at = 15;
   */
  revokedAt?: Timestamp;
};

/**
 * Describes the message admiral.common.v1.AccessToken.
 * Use `create(AccessTokenSchema)` to create a new message.
 */
export const AccessTokenSchema: GenMessage<AccessToken> = /*@__PURE__*/
  messageDesc(file_admiral_common_v1_token, 0);

/**
 * TokenType identifies the category of an access token issued by Admiral's token system.
 * IDP-issued JWTs (OAuth2/OIDC sessions) are NOT represented here — they are
 * resolved by separate middleware and can be referenced as "session" in
 * AuthRule.allowed_token_types when needed.
 *
 * @generated from enum admiral.common.v1.TokenType
 */
export enum TokenType {
  /**
   * Default value. Must not be used.
   *
   * @generated from enum value: TOKEN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Personal Access Token, bound to a user.
   *
   * @generated from enum value: TOKEN_TYPE_PAT = 1;
   */
  PAT = 1,

  /**
   * Agent Token, bound to a cluster or runner.
   *
   * @generated from enum value: TOKEN_TYPE_AGT = 2;
   */
  AGT = 2,
}

/**
 * Describes the enum admiral.common.v1.TokenType.
 */
export const TokenTypeSchema: GenEnum<TokenType> = /*@__PURE__*/
  enumDesc(file_admiral_common_v1_token, 0);

/**
 * BindingType identifies the kind of resource an access token is bound to.
 *
 * @generated from enum admiral.common.v1.BindingType
 */
export enum BindingType {
  /**
   * Default value. Must not be used.
   *
   * @generated from enum value: BINDING_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Token is bound to a user (PATs).
   *
   * @generated from enum value: BINDING_TYPE_USER = 1;
   */
  USER = 1,

  /**
   * Token is bound to a cluster (AGTs).
   *
   * @generated from enum value: BINDING_TYPE_CLUSTER = 2;
   */
  CLUSTER = 2,

  /**
   * Token is bound to a runner (AGTs).
   *
   * @generated from enum value: BINDING_TYPE_RUNNER = 3;
   */
  RUNNER = 3,
}

/**
 * Describes the enum admiral.common.v1.BindingType.
 */
export const BindingTypeSchema: GenEnum<BindingType> = /*@__PURE__*/
  enumDesc(file_admiral_common_v1_token, 1);

/**
 * AccessTokenStatus represents the lifecycle state of an access token.
 *
 * @generated from enum admiral.common.v1.AccessTokenStatus
 */
export enum AccessTokenStatus {
  /**
   * Default value. Must not be used.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The token is valid and can be used for authentication.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * The token has been permanently revoked and cannot be used.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_REVOKED = 2;
   */
  REVOKED = 2,

  /**
   * The token is being rotated. Both old and new tokens are valid
   * until the grace period expires.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_ROTATING = 3;
   */
  ROTATING = 3,
}

/**
 * Describes the enum admiral.common.v1.AccessTokenStatus.
 */
export const AccessTokenStatusSchema: GenEnum<AccessTokenStatus> = /*@__PURE__*/
  enumDesc(file_admiral_common_v1_token, 2);

