// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file healthcheck/v1/healthcheck.proto (package admiral.api.healthcheck.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file healthcheck/v1/healthcheck.proto.
 */
export const file_healthcheck_v1_healthcheck: GenFile = /*@__PURE__*/
  fileDesc("CiBoZWFsdGhjaGVjay92MS9oZWFsdGhjaGVjay5wcm90bxIaYWRtaXJhbC5hcGkuaGVhbHRoY2hlY2sudjEiFAoSSGVhbHRoY2hlY2tSZXF1ZXN0IhUKE0hlYWx0aGNoZWNrUmVzcG9uc2UypgEKDkhlYWx0aGNoZWNrQVBJEpMBCgtIZWFsdGhjaGVjaxIuLmFkbWlyYWwuYXBpLmhlYWx0aGNoZWNrLnYxLkhlYWx0aGNoZWNrUmVxdWVzdBovLmFkbWlyYWwuYXBpLmhlYWx0aGNoZWNrLnYxLkhlYWx0aGNoZWNrUmVzcG9uc2UiI4LT5JMCHVoKEggvaGVhbHRoehIPL3YxL2hlYWx0aGNoZWNrQvMBCh5jb20uYWRtaXJhbC5hcGkuaGVhbHRoY2hlY2sudjFCEEhlYWx0aGNoZWNrUHJvdG9QAVo0Z28uYWRtaXJhbC5pby9zZGsvcHJvdG8vaGVhbHRoY2hlY2svdjE7aGVhbHRoY2hlY2t2MaICA0FBSKoCGkFkbWlyYWwuQXBpLkhlYWx0aGNoZWNrLlYxygIaQWRtaXJhbFxBcGlcSGVhbHRoY2hlY2tcVjHiAiZBZG1pcmFsXEFwaVxIZWFsdGhjaGVja1xWMVxHUEJNZXRhZGF0YeoCHUFkbWlyYWw6OkFwaTo6SGVhbHRoY2hlY2s6OlYxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * HealthcheckRequest is the request message for Healthcheck.
 * No parameters are required.
 *
 * @generated from message admiral.api.healthcheck.v1.HealthcheckRequest
 */
export type HealthcheckRequest = Message<"admiral.api.healthcheck.v1.HealthcheckRequest"> & {
};

/**
 * Describes the message admiral.api.healthcheck.v1.HealthcheckRequest.
 * Use `create(HealthcheckRequestSchema)` to create a new message.
 */
export const HealthcheckRequestSchema: GenMessage<HealthcheckRequest> = /*@__PURE__*/
  messageDesc(file_healthcheck_v1_healthcheck, 0);

/**
 * HealthcheckResponse is returned when the service is healthy.
 * An empty response indicates the service is operating normally.
 *
 * @generated from message admiral.api.healthcheck.v1.HealthcheckResponse
 */
export type HealthcheckResponse = Message<"admiral.api.healthcheck.v1.HealthcheckResponse"> & {
};

/**
 * Describes the message admiral.api.healthcheck.v1.HealthcheckResponse.
 * Use `create(HealthcheckResponseSchema)` to create a new message.
 */
export const HealthcheckResponseSchema: GenMessage<HealthcheckResponse> = /*@__PURE__*/
  messageDesc(file_healthcheck_v1_healthcheck, 1);

/**
 * HealthcheckAPI provides health check operations for monitoring service availability.
 *
 * @generated from service admiral.api.healthcheck.v1.HealthcheckAPI
 */
export const HealthcheckAPI: GenService<{
  /**
   * Healthcheck verifies that the service is running and healthy.
   * Returns an empty response on success. Use this endpoint for load balancer
   * health checks and monitoring systems.
   *
   * @generated from rpc admiral.api.healthcheck.v1.HealthcheckAPI.Healthcheck
   */
  healthcheck: {
    methodKind: "unary";
    input: typeof HealthcheckRequestSchema;
    output: typeof HealthcheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_healthcheck_v1_healthcheck, 0);

