// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file accesstoken/v1/accesstoken.proto (package admiral.api.accesstoken.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TokenType } from "../../authz/v1/annotations_pb";
import { file_authz_v1_annotations } from "../../authz/v1/annotations_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accesstoken/v1/accesstoken.proto.
 */
export const file_accesstoken_v1_accesstoken: GenFile = /*@__PURE__*/
  fileDesc("CiBhY2Nlc3N0b2tlbi92MS9hY2Nlc3N0b2tlbi5wcm90bxIaYWRtaXJhbC5hcGkuYWNjZXNzdG9rZW4udjEimgQKC0FjY2Vzc1Rva2VuEhQKAmlkGAEgASgJQgi6SAVyA7ABARIbCgl0ZW5hbnRfaWQYAiABKAlCCLpIBXIDsAEBEhQKDGRpc3BsYXlfbmFtZRgDIAEoCRIUCgx0b2tlbl9wcmVmaXgYBCABKAkSMwoKdG9rZW5fdHlwZRgFIAEoDjIfLmFkbWlyYWwuYXBpLmF1dGh6LnYxLlRva2VuVHlwZRIOCgZzY29wZXMYBiADKAkSPQoGc3RhdHVzGAcgASgOMi0uYWRtaXJhbC5hcGkuYWNjZXNzdG9rZW4udjEuQWNjZXNzVG9rZW5TdGF0dXMSDwoHdXNlcl9pZBgIIAEoCRIaChJzZXJ2aWNlX2FjY291bnRfaWQYCSABKAkSEgoKY2x1c3Rlcl9pZBgKIAEoCRIRCglydW5uZXJfaWQYCyABKAkSEgoKY3JlYXRlZF9ieRgMIAEoCRIuCgpleHBpcmVzX2F0GA0gASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxsYXN0X3VzZWRfYXQYDiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmNyZWF0ZWRfYXQYDyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnJldm9rZWRfYXQYECABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKpsBChFBY2Nlc3NUb2tlblN0YXR1cxIjCh9BQ0NFU1NfVE9LRU5fU1RBVFVTX1VOU1BFQ0lGSUVEEAASHgoaQUNDRVNTX1RPS0VOX1NUQVRVU19BQ1RJVkUQARIfChtBQ0NFU1NfVE9LRU5fU1RBVFVTX1JFVk9LRUQQAhIgChxBQ0NFU1NfVE9LRU5fU1RBVFVTX1JPVEFUSU5HEANC8wEKHmNvbS5hZG1pcmFsLmFwaS5hY2Nlc3N0b2tlbi52MUIQQWNjZXNzdG9rZW5Qcm90b1ABWjRnby5hZG1pcmFsLmlvL3Nkay9wcm90by9hY2Nlc3N0b2tlbi92MTthY2Nlc3N0b2tlbnYxogIDQUFBqgIaQWRtaXJhbC5BcGkuQWNjZXNzdG9rZW4uVjHKAhpBZG1pcmFsXEFwaVxBY2Nlc3N0b2tlblxWMeICJkFkbWlyYWxcQXBpXEFjY2Vzc3Rva2VuXFYxXEdQQk1ldGFkYXRh6gIdQWRtaXJhbDo6QXBpOjpBY2Nlc3N0b2tlbjo6VjFiBnByb3RvMw", [file_authz_v1_annotations, file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * AccessToken contains token metadata common to all token types (PAT, SAT, AGT).
 * The raw token secret is never included in this message — it is only returned
 * once at creation time via the `plain_text_token` field in Create responses.
 *
 * Token CRUD is managed by each parent resource's API:
 *   - PATs:         UserAPI            (/v1/user/tokens)
 *   - SATs:         ServiceAccountAPI  (/v1/service-accounts/{id}/tokens)
 *   - Cluster AGTs: ClusterAPI         (/v1/clusters/{id}/tokens)
 *   - Runner AGTs:  RunnerAPI          (/v1/runners/{id}/tokens)
 *
 * @generated from message admiral.api.accesstoken.v1.AccessToken
 */
export type AccessToken = Message<"admiral.api.accesstoken.v1.AccessToken"> & {
  /**
   * Unique identifier for the token (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Tenant this token belongs to (UUID).
   *
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * Human-readable name for the token (e.g., "postman-testing", "ci-deploy-key").
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Display-safe prefix for identifying the token without exposing the secret
   * (e.g., "adm_pat_7kH3").
   *
   * @generated from field: string token_prefix = 4;
   */
  tokenPrefix: string;

  /**
   * The category of this token.
   *
   * @generated from field: admiral.api.authz.v1.TokenType token_type = 5;
   */
  tokenType: TokenType;

  /**
   * The scopes granted to this token. For PATs and SATs, these are user-selected.
   * For AGTs, these are auto-assigned based on the resource type.
   *
   * @generated from field: repeated string scopes = 6;
   */
  scopes: string[];

  /**
   * Current lifecycle status of the token.
   *
   * @generated from field: admiral.api.accesstoken.v1.AccessTokenStatus status = 7;
   */
  status: AccessTokenStatus;

  /**
   * The user this token is bound to (UUID). Set when token_type is
   * PERSONAL_ACCESS_TOKEN.
   *
   * @generated from field: string user_id = 8;
   */
  userId: string;

  /**
   * The service account this token is bound to (UUID). Set when token_type is
   * SERVICE_ACCOUNT_TOKEN.
   *
   * @generated from field: string service_account_id = 9;
   */
  serviceAccountId: string;

  /**
   * The cluster this token is bound to (UUID). Set when token_type is
   * AGENT_TOKEN and the token is bound to a cluster.
   *
   * @generated from field: string cluster_id = 10;
   */
  clusterId: string;

  /**
   * The runner this token is bound to (UUID). Set when token_type is
   * AGENT_TOKEN and the token is bound to a runner.
   *
   * @generated from field: string runner_id = 11;
   */
  runnerId: string;

  /**
   * The user who created this token (UUID). For PATs, this is the token owner.
   * For SATs and AGTs, this is the administrator who issued the token.
   *
   * @generated from field: string created_by = 12;
   */
  createdBy: string;

  /**
   * When the token expires. If unset, the token does not expire.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 13;
   */
  expiresAt?: Timestamp;

  /**
   * When the token was last used to authenticate an API request.
   *
   * @generated from field: google.protobuf.Timestamp last_used_at = 14;
   */
  lastUsedAt?: Timestamp;

  /**
   * When the token was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 15;
   */
  createdAt?: Timestamp;

  /**
   * When the token was revoked. Only set when status is REVOKED.
   *
   * @generated from field: google.protobuf.Timestamp revoked_at = 16;
   */
  revokedAt?: Timestamp;
};

/**
 * Describes the message admiral.api.accesstoken.v1.AccessToken.
 * Use `create(AccessTokenSchema)` to create a new message.
 */
export const AccessTokenSchema: GenMessage<AccessToken> = /*@__PURE__*/
  messageDesc(file_accesstoken_v1_accesstoken, 0);

/**
 * AccessTokenStatus represents the lifecycle state of an access token.
 *
 * @generated from enum admiral.api.accesstoken.v1.AccessTokenStatus
 */
export enum AccessTokenStatus {
  /**
   * Default value. Must not be used.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The token is valid and can be used for authentication.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * The token has been permanently revoked and cannot be used.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_REVOKED = 2;
   */
  REVOKED = 2,

  /**
   * The token is being rotated. Both old and new tokens are valid
   * until the grace period expires.
   *
   * @generated from enum value: ACCESS_TOKEN_STATUS_ROTATING = 3;
   */
  ROTATING = 3,
}

/**
 * Describes the enum admiral.api.accesstoken.v1.AccessTokenStatus.
 */
export const AccessTokenStatusSchema: GenEnum<AccessTokenStatus> = /*@__PURE__*/
  enumDesc(file_accesstoken_v1_accesstoken, 0);

