// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file openapi.proto (package admiral.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gnostic_openapi_v3_annotations } from "./gnostic/openapi/v3/annotations_pb";

/**
 * Describes the file openapi.proto.
 */
export const file_openapi: GenFile = /*@__PURE__*/
  fileDesc("Cg1vcGVuYXBpLnByb3RvEg5hZG1pcmFsLmFwaS52MULBAQoSY29tLmFkbWlyYWwuYXBpLnYxQgxPcGVuYXBpUHJvdG9QAVodZ28uYWRtaXJhbC5pby9zZGsvcHJvdG87YXBpdjGiAgNBQViqAg5BZG1pcmFsLkFwaS5WMcoCDkFkbWlyYWxcQXBpXFYx4gIaQWRtaXJhbFxBcGlcVjFcR1BCTWV0YWRhdGHqAhBBZG1pcmFsOjpBcGk6OlYxukcjEiEKC0FkbWlyYWwgQVBJEgtBZG1pcmFsIEFQSTIFMC4wLjBiBnByb3RvMw", [file_gnostic_openapi_v3_annotations]);

