// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file admiral/healthcheck/v1/healthcheck.proto (package admiral.healthcheck.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_admiral_common_v1_annotations } from "../../common/v1/annotations_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admiral/healthcheck/v1/healthcheck.proto.
 */
export const file_admiral_healthcheck_v1_healthcheck: GenFile = /*@__PURE__*/
  fileDesc("CihhZG1pcmFsL2hlYWx0aGNoZWNrL3YxL2hlYWx0aGNoZWNrLnByb3RvEhZhZG1pcmFsLmhlYWx0aGNoZWNrLnYxIhQKEkhlYWx0aGNoZWNrUmVxdWVzdCIVChNIZWFsdGhjaGVja1Jlc3BvbnNlMqIBCg5IZWFsdGhjaGVja0FQSRKPAQoLSGVhbHRoY2hlY2sSKi5hZG1pcmFsLmhlYWx0aGNoZWNrLnYxLkhlYWx0aGNoZWNrUmVxdWVzdBorLmFkbWlyYWwuaGVhbHRoY2hlY2sudjEuSGVhbHRoY2hlY2tSZXNwb25zZSInqJckAYLT5JMCHVoKEggvaGVhbHRoehIPL3YxL2hlYWx0aGNoZWNrQuYBChpjb20uYWRtaXJhbC5oZWFsdGhjaGVjay52MUIQSGVhbHRoY2hlY2tQcm90b1ABWjxnby5hZG1pcmFsLmlvL3Nkay9wcm90by9hZG1pcmFsL2hlYWx0aGNoZWNrL3YxO2hlYWx0aGNoZWNrdjGiAgNBSFiqAhZBZG1pcmFsLkhlYWx0aGNoZWNrLlYxygIWQWRtaXJhbFxIZWFsdGhjaGVja1xWMeICIkFkbWlyYWxcSGVhbHRoY2hlY2tcVjFcR1BCTWV0YWRhdGHqAhhBZG1pcmFsOjpIZWFsdGhjaGVjazo6VjFiBnByb3RvMw", [file_admiral_common_v1_annotations, file_google_api_annotations]);

/**
 * HealthcheckRequest is the request message for the Healthcheck RPC.
 * No parameters are required.
 *
 * @generated from message admiral.healthcheck.v1.HealthcheckRequest
 */
export type HealthcheckRequest = Message<"admiral.healthcheck.v1.HealthcheckRequest"> & {
};

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckRequest.
 * Use `create(HealthcheckRequestSchema)` to create a new message.
 */
export const HealthcheckRequestSchema: GenMessage<HealthcheckRequest> = /*@__PURE__*/
  messageDesc(file_admiral_healthcheck_v1_healthcheck, 0);

/**
 * HealthcheckResponse is returned when the service is healthy. An empty
 * response with an OK status code indicates the service is available.
 *
 * @generated from message admiral.healthcheck.v1.HealthcheckResponse
 */
export type HealthcheckResponse = Message<"admiral.healthcheck.v1.HealthcheckResponse"> & {
};

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckResponse.
 * Use `create(HealthcheckResponseSchema)` to create a new message.
 */
export const HealthcheckResponseSchema: GenMessage<HealthcheckResponse> = /*@__PURE__*/
  messageDesc(file_admiral_healthcheck_v1_healthcheck, 1);

/**
 * HealthcheckAPI provides health check operations for monitoring service availability.
 *
 * @generated from service admiral.healthcheck.v1.HealthcheckAPI
 */
export const HealthcheckAPI: GenService<{
  /**
   * Healthcheck verifies that the service is running and healthy.
   * Returns an empty response on success. Use this endpoint for load balancer
   * health checks and monitoring systems.
   *
   * No authentication required — this is a public endpoint.
   *
   * @generated from rpc admiral.healthcheck.v1.HealthcheckAPI.Healthcheck
   */
  healthcheck: {
    methodKind: "unary";
    input: typeof HealthcheckRequestSchema;
    output: typeof HealthcheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admiral_healthcheck_v1_healthcheck, 0);

