// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file user/v1/user.proto (package admiral.api.user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SE2FkbWlyYWwuYXBpLnVzZXIudjEiEAoOR2V0VXNlclJlcXVlc3Qi5QEKD0dldFVzZXJSZXNwb25zZRIKCgJpZBgBIAEoCRIRCgl0ZW5hbnRfaWQYAiABKAkSDQoFZW1haWwYAyABKAkSGQoMZGlzcGxheV9uYW1lGAQgASgJSACIAQESFwoKZ2l2ZW5fbmFtZRgFIAEoCUgBiAEBEhgKC2ZhbWlseV9uYW1lGAYgASgJSAKIAQESFwoKYXZhdGFyX3VybBgHIAEoCUgDiAEBQg8KDV9kaXNwbGF5X25hbWVCDQoLX2dpdmVuX25hbWVCDgoMX2ZhbWlseV9uYW1lQg0KC19hdmF0YXJfdXJsMnEKB1VzZXJBUEkSZgoHR2V0VXNlchIjLmFkbWlyYWwuYXBpLnVzZXIudjEuR2V0VXNlclJlcXVlc3QaJC5hZG1pcmFsLmFwaS51c2VyLnYxLkdldFVzZXJSZXNwb25zZSIQgtPkkwIKEggvdjEvdXNlckK7AQoXY29tLmFkbWlyYWwuYXBpLnVzZXIudjFCCVVzZXJQcm90b1ABWiZnby5hZG1pcmFsLmlvL3Nkay9wcm90by91c2VyL3YxO3VzZXJ2MaICA0FBVaoCE0FkbWlyYWwuQXBpLlVzZXIuVjHKAhNBZG1pcmFsXEFwaVxVc2VyXFYx4gIfQWRtaXJhbFxBcGlcVXNlclxWMVxHUEJNZXRhZGF0YeoCFkFkbWlyYWw6OkFwaTo6VXNlcjo6VjFiBnByb3RvMw", [file_google_api_annotations]);

/**
 * GetUserRequest is the request message for GetUser.
 * No parameters are required as the user is identified by the auth token.
 *
 * @generated from message admiral.api.user.v1.GetUserRequest
 */
export type GetUserRequest = Message<"admiral.api.user.v1.GetUserRequest"> & {
};

/**
 * Describes the message admiral.api.user.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * GetUserResponse contains the authenticated user's profile information.
 *
 * @generated from message admiral.api.user.v1.GetUserResponse
 */
export type GetUserResponse = Message<"admiral.api.user.v1.GetUserResponse"> & {
  /**
   * Unique identifier for the user (UUID format).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The tenant/organization this user belongs to (UUID format).
   *
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * User's email address.
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * User's display name for UI purposes.
   *
   * @generated from field: optional string display_name = 4;
   */
  displayName?: string;

  /**
   * User's given (first) name.
   *
   * @generated from field: optional string given_name = 5;
   */
  givenName?: string;

  /**
   * User's family (last) name.
   *
   * @generated from field: optional string family_name = 6;
   */
  familyName?: string;

  /**
   * URL to the user's avatar image.
   *
   * @generated from field: optional string avatar_url = 7;
   */
  avatarUrl?: string;
};

/**
 * Describes the message admiral.api.user.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

/**
 * UserAPI provides operations for retrieving user profile information.
 *
 * @generated from service admiral.api.user.v1.UserAPI
 */
export const UserAPI: GenService<{
  /**
   * GetUser retrieves the profile of the currently authenticated user.
   * The user is identified by the authentication token provided in the request.
   *
   * @generated from rpc admiral.api.user.v1.UserAPI.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_user, 0);

