// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file authz/v1/annotations.proto (package admiral.api.authz.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file authz/v1/annotations.proto.
 */
export const file_authz_v1_annotations: GenFile = /*@__PURE__*/
  fileDesc("ChphdXRoei92MS9hbm5vdGF0aW9ucy5wcm90bxIUYWRtaXJhbC5hcGkuYXV0aHoudjEiNgoIQXV0aFJ1bGUSDQoFc2NvcGUYASABKAkSGwoTYWxsb3dlZF90b2tlbl90eXBlcxgCIAMoCSpuCglUb2tlblR5cGUSGgoWVE9LRU5fVFlQRV9VTlNQRUNJRklFRBAAEhkKFVBFUlNPTkFMX0FDQ0VTU19UT0tFThABEhkKFVNFUlZJQ0VfQUNDT1VOVF9UT0tFThACEg8KC0FHRU5UX1RPS0VOEAM6VwoEcnVsZRIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGNCGAyABKAsyHi5hZG1pcmFsLmFwaS5hdXRoei52MS5BdXRoUnVsZVIEcnVsZYgBAULJAQoYY29tLmFkbWlyYWwuYXBpLmF1dGh6LnYxQhBBbm5vdGF0aW9uc1Byb3RvUAFaKGdvLmFkbWlyYWwuaW8vc2RrL3Byb3RvL2F1dGh6L3YxO2F1dGh6djGiAgNBQUGqAhRBZG1pcmFsLkFwaS5BdXRoei5WMcoCFEFkbWlyYWxcQXBpXEF1dGh6XFYx4gIgQWRtaXJhbFxBcGlcQXV0aHpcVjFcR1BCTWV0YWRhdGHqAhdBZG1pcmFsOjpBcGk6OkF1dGh6OjpWMWIGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * AuthRule defines the authorization requirements for an RPC method.
 * Applied as a custom method option and enforced at runtime by a Connect interceptor.
 *
 * The presence of the option means the RPC requires authentication.
 * An empty scope means any authenticated request is sufficient.
 *
 * @generated from message admiral.api.authz.v1.AuthRule
 */
export type AuthRule = Message<"admiral.api.authz.v1.AuthRule"> & {
  /**
   * The scope required to call this RPC (e.g., "clusters:read").
   * Empty string means any valid token is sufficient — no specific scope required.
   *
   * @generated from field: string scope = 1;
   */
  scope: string;

  /**
   * Restrict to specific token types ("pat", "sat", "agt", "session").
   * Empty means all token types are allowed.
   *
   * @generated from field: repeated string allowed_token_types = 2;
   */
  allowedTokenTypes: string[];
};

/**
 * Describes the message admiral.api.authz.v1.AuthRule.
 * Use `create(AuthRuleSchema)` to create a new message.
 */
export const AuthRuleSchema: GenMessage<AuthRule> = /*@__PURE__*/
  messageDesc(file_authz_v1_annotations, 0);

/**
 * TokenType identifies the category of an access token issued by Admiral's token system.
 * IDP-issued JWTs (OAuth2/OIDC sessions) are NOT represented here — they are
 * resolved by separate middleware and can be referenced as "session" in
 * AuthRule.allowed_token_types when needed.
 *
 * @generated from enum admiral.api.authz.v1.TokenType
 */
export enum TokenType {
  /**
   * @generated from enum value: TOKEN_TYPE_UNSPECIFIED = 0;
   */
  TOKEN_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN = 1;
   */
  PERSONAL_ACCESS_TOKEN = 1,

  /**
   * @generated from enum value: SERVICE_ACCOUNT_TOKEN = 2;
   */
  SERVICE_ACCOUNT_TOKEN = 2,

  /**
   * @generated from enum value: AGENT_TOKEN = 3;
   */
  AGENT_TOKEN = 3,
}

/**
 * Describes the enum admiral.api.authz.v1.TokenType.
 */
export const TokenTypeSchema: GenEnum<TokenType> = /*@__PURE__*/
  enumDesc(file_authz_v1_annotations, 0);

/**
 * @generated from extension: optional admiral.api.authz.v1.AuthRule rule = 50000;
 */
export const rule: GenExtension<MethodOptions, AuthRule> = /*@__PURE__*/
  extDesc(file_authz_v1_annotations, 0);

